# Generated by Django 2.2.12 on 2020-07-08 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, help_text='Profile Picture', null=True, upload_to='user_e/')),
                ('first_name', models.CharField(help_text='Enter First Name', max_length=100)),
                ('last_name', models.CharField(help_text='Enter Last Name', max_length=100)),
                ('date_of_birth', models.DateField()),
                ('skills', models.TextField(help_text='List Your Skills', max_length=255)),
                ('email', models.EmailField(help_text='Enter Email', max_length=254)),
                ('mobile', models.CharField(help_text='Enter Mobile Number', max_length=255)),
                ('id_number', models.CharField(help_text='Enter ID Number', max_length=255)),
                ('passport_number', models.CharField(blank='True', help_text='Enter Passport Number', max_length=255, null='True')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', help_text='Select Your Gender', max_length=255)),
                ('status', models.CharField(choices=[('DR', 'Dropped Out'), ('SC', 'Schooling'), ('YT', 'Yet To graduate'), ('GR', 'graduated')], default='GR', help_text='Education Progress', max_length=100)),
                ('level', models.CharField(choices=[('C', 'Certificate'), ('D', 'Diploma'), ('HD', 'Higher-Diploma'), ('D', 'Degree'), ('M', 'Masters'), ('DR', 'Doctorate'), ('PHD', 'Professor')], default='D', help_text='Academic Level', max_length=100)),
                ('language', models.CharField(choices=[('ksw', 'Kiswahil'), ('eng', 'English'), ('shg', 'Sheng'), ('lhy', 'Luhya'), ('kky', 'Kikuyu')], default='ksw', help_text='Fluet Language', max_length=100)),
                ('location', models.CharField(choices=[('ky', 'Kenya'), ('ug', 'Uganda'), ('tz', 'Tanzania'), ('rw', 'Rwanda'), ('sd', 'Sudan'), ('ng', 'Nigeria'), ('gh', 'Ghana')], default='ky', help_text='Your country', max_length=100)),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='Cover_Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_attachment', models.FileField(help_text='Attach Your Curriculum Vitae', upload_to='uploads/cvs/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, help_text='Profile Picture', null=True, upload_to='user_e/')),
                ('company_name', models.CharField(help_text='Employer Name', max_length=255)),
                ('email', models.EmailField(help_text='Official Email', max_length=254)),
                ('mobile', models.CharField(help_text='Enter Mobile Number', max_length=255)),
                ('location', models.CharField(help_text='Enter Company Location', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Enter Full Names', max_length=255)),
                ('mobile', models.CharField(help_text='Enter Number', max_length=255)),
                ('email', models.EmailField(help_text='Enter Email', max_length=254)),
                ('applicant', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.PROTECT, related_name='referees', to='job.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank='True', max_length=255, null='True')),
                ('course', models.CharField(blank='True', max_length=254, null='True')),
                ('major', models.CharField(max_length=100)),
                ('achivement', models.TextField(help_text='Enter Attainment', max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qualifications', to='job.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(help_text='Enter Job Title', max_length=255)),
                ('ref_no', models.CharField(help_text='Enter Job Ref Number', max_length=255)),
                ('industry', models.CharField(max_length=254)),
                ('summary', models.TextField(help_text='Job Summary', max_length=255)),
                ('description_detail', models.TextField(help_text='Detailed Job Description', max_length=254)),
                ('education', models.CharField(help_text='Education Level', max_length=254)),
                ('experience', models.TextField(help_text='Preferred Experience', max_length=255)),
                ('skills', models.TextField(help_text='Desired Skills', max_length=254)),
                ('terms_conditions', models.TextField(max_length=255)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('application_deadline', models.DateTimeField()),
                ('station', models.CharField(choices=[('Nrb', 'Nairobi'), ('Msa', 'Mombasa'), ('Mch', 'Machakos'), ('Ksm', 'Kisumu'), ('Eld', 'Eldoret'), ('Nks', 'Nakuru'), ('Thk', 'Thika')], default='Nrb', help_text='Where The Job Is Located', max_length=100)),
                ('contract', models.CharField(choices=[('per', 'permanent'), ('ren', 'Renewable'), ('Int', 'Internship'), ('Att', 'Attachment')], default='per', help_text='Type of Employment', max_length=100)),
                ('employer', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='job.Employer')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employed', models.BooleanField(default=False, help_text='Are You Employed?')),
                ('current_employer', models.CharField(max_length=254)),
                ('last_employer', models.CharField(max_length=254)),
                ('job_title', models.CharField(help_text='Name Your Specialisation', max_length=250)),
                ('responsibilities', models.TextField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('applicant', models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, related_name='experiences', to='job.Applicant')),
            ],
        ),
    ]
